server:
  port: 8460
spring:
  application:
    name: search-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8