server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/api/doc/**
          filters:
            - StripPrefix=2
        - id: information-service
          uri: lb://information-service
          predicates:
            - Path=/api/info/**
          filters:
            - StripPrefix=2
        - id: personnel-service
          uri: lb://personnel-service
          predicates:
            - Path=/api/pers/**
          filters:
            - StripPrefix=2
    nacos:
      discovery:
        server-addr: localhost:8848
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: localhost:8846/key/public
  jackson:
    default-property-inclusion: non_null