server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: oauth-service
          uri: lb://oauth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
            - AddRequestParameter=client_id, oasys
            - AddRequestParameter=client_secret, linter
            - AddRequestParameter=grant_type, password
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: netdisk-service
          uri: lb://netdisk-service
          predicates:
            - Path=/api/netdisk/**
          filters:
            - StripPrefix=2
        - id: announcement-service
          uri: lb://announcement-service
          predicates:
            - Path=/api/announcement/**
          filters:
            - StripPrefix=2
    nacos:
      discovery:
        server-addr: localhost:8848
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: localhost:8846/key/public
