server:
  port: 8420
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  application:
    name: netdisk-service
  servlet:
    multipart:
      max-file-size: 50MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    password: root
    url: jdbc:mysql://localhost/oasys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
minio:
  endpoint: http://localhost:9000
  bucketName: net-disk
  accessKey: oasys
  secretKey: linter.cn
logging:
  level:
    cn.linter.oasys.netdisk.dao: debug