server:
  port: 8450
spring:
  application:
    name: chat-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  kafka:
    consumer:
      group-id: chat
      auto-offset-reset: earliest